### ISSUE TITLE
이 저장소 운영되는 것 맞나요?

### ISSUE THREAD

**Issue by rlarjsdn122** [git-l10n-ko/git-l10n-ko#17]
마지막 병합도 작년이고 저장소 갱신도 작년이 마지막이네요. 
git-l10n/git-po 포크해서 수정한 다음에 여기 올리려하니까 다른 기록철도 같이 갱신되서 수정 내역이 꼬일 것 같습니다...

**Comment by elongbug** [comment]
안녕하세요.  개인적인 사정으로 지난해 이후 갱신이 없었습니다.
문의 주신 컨플릿 문제는 2.23.0 버전으로 머지후 여기에 커맨트 남기겠습니다.
Ping 주셔서 감사합니다.

**Comment by elongbug** [comment]
ko/master branch로 upstream merge되었습니다. 해당 브랜치는 변역하시는 분들의 git history가 같이 기록되는 branch로 해당 브랜치를 clone해서 작업하시면 됩니다. 이후 번역 commit들은 squash되어 하나의 커밋으로 git-l10n/git-po로 PR이 되는 프로세스입니다.

**Comment by rlarjsdn122** [comment]
네, 감사합니다.
